
// This file has been generated by the GUI designer. Do not modify.
namespace LynnaLab
{
	public partial class ObjectGroupEditor
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Label label1;

		private global::Gtk.SpinButton indexSpinButton;

		private global::Gtk.Button addButton;

		private global::Gtk.Button deleteButton;

		private global::Gtk.Frame frame2;

		private global::Gtk.Alignment GtkAlignment1;

		private global::Gtk.Alignment objectDataContainer;

		private global::Gtk.Label frameLabel;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget LynnaLab.ObjectGroupEditor
			global::Stetic.BinContainer.Attach(this);
			this.Name = "LynnaLab.ObjectGroupEditor";
			// Container child LynnaLab.ObjectGroupEditor.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Object Index");
			this.hbox1.Add(this.label1);
            hbox1.SetChildPacking(label1, false, false, 0, Gtk.PackType.Start);
			// Container child hbox1.Gtk.Box+BoxChild
			this.indexSpinButton = new global::Gtk.SpinButton(0D, 100D, 1D);
			this.indexSpinButton.Name = "indexSpinButton";
			this.indexSpinButton.Adjustment.PageIncrement = 10D;
			this.indexSpinButton.ClimbRate = 1D;
			this.indexSpinButton.Numeric = true;
			this.hbox1.Add(this.indexSpinButton);
            hbox1.SetChildPacking(indexSpinButton, false, false, 0, Gtk.PackType.Start);
			// Container child hbox1.Gtk.Box+BoxChild
			this.addButton = new global::Gtk.Button();
			this.addButton.CanFocus = true;
			this.addButton.Name = "addButton";
			this.addButton.UseStock = true;
			this.addButton.UseUnderline = true;
			this.addButton.FocusOnClick = false;
			this.addButton.Label = "gtk-add";
			this.hbox1.Add(this.addButton);
            hbox1.SetChildPacking(addButton, false, false, 0, Gtk.PackType.Start);
			// Container child hbox1.Gtk.Box+BoxChild
			this.deleteButton = new global::Gtk.Button();
			this.deleteButton.CanFocus = true;
			this.deleteButton.Name = "deleteButton";
			this.deleteButton.UseStock = true;
			this.deleteButton.UseUnderline = true;
			this.deleteButton.FocusOnClick = false;
			this.deleteButton.Label = "gtk-remove";
			this.hbox1.Add(this.deleteButton);
            hbox1.SetChildPacking(deleteButton, false, false, 0, Gtk.PackType.Start);
			this.vbox1.Add(this.hbox1);
            vbox1.SetChildPacking(hbox1, false, false, 0, Gtk.PackType.Start);
			// Container child vbox1.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame();
			this.frame2.Name = "frame2";
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment(0F, 0F, 1F, 0F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.objectDataContainer = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.objectDataContainer.Name = "objectDataContainer";
			this.GtkAlignment1.Add(this.objectDataContainer);
			this.frame2.Add(this.GtkAlignment1);
			this.frameLabel = new global::Gtk.Label();
			this.frameLabel.Name = "frameLabel";
			this.frameLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Object");
			this.frameLabel.UseMarkup = true;
			this.frame2.LabelWidget = this.frameLabel;
			this.vbox1.Add(this.frame2);
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
			this.addButton.Clicked += new global::System.EventHandler(this.OnAddButtonClicked);
			this.deleteButton.Clicked += new global::System.EventHandler(this.OnDeleteButtonClicked);
		}
	}
}
