
// This file has been generated by the GUI designer. Do not modify.
namespace LynnaLab
{
	public partial class AreaEditor
	{
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Label label7;
		
		private global::LynnaLab.SpinButtonHexadecimal areaSpinButton;
		
		private global::Gtk.Frame frame2;
		
		private global::Gtk.Alignment GtkAlignment;
		
		private global::Gtk.Table table2;
		
		private global::LynnaLab.SpinButtonHexadecimal flags1SpinButton;
		
		private global::LynnaLab.SpinButtonHexadecimal flags2SpinButton;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.Label label6;
		
		private global::Gtk.Label GtkLabel;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LynnaLab.AreaEditor
			global::Stetic.BinContainer.Attach (this);
			this.Name = "LynnaLab.AreaEditor";
			// Container child LynnaLab.AreaEditor.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Area");
			this.hbox2.Add (this.label7);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label7]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.areaSpinButton = new global::LynnaLab.SpinButtonHexadecimal ();
			this.areaSpinButton.CanFocus = true;
			this.areaSpinButton.Name = "areaSpinButton";
			this.areaSpinButton.Adjustment.Upper = 255;
			this.areaSpinButton.Adjustment.PageIncrement = 10;
			this.areaSpinButton.Adjustment.StepIncrement = 1;
			this.areaSpinButton.ClimbRate = 1;
			this.areaSpinButton.Digits = ((uint)(2));
			this.areaSpinButton.Numeric = true;
			this.hbox2.Add (this.areaSpinButton);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.areaSpinButton]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.vbox2.Add (this.hbox2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.table2 = new global::Gtk.Table (((uint)(3)), ((uint)(2)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.flags1SpinButton = new global::LynnaLab.SpinButtonHexadecimal ();
			this.flags1SpinButton.CanFocus = true;
			this.flags1SpinButton.Name = "flags1SpinButton";
			this.flags1SpinButton.Adjustment.Upper = 255;
			this.flags1SpinButton.Adjustment.PageIncrement = 10;
			this.flags1SpinButton.Adjustment.StepIncrement = 1;
			this.flags1SpinButton.ClimbRate = 1;
			this.flags1SpinButton.Digits = ((uint)(2));
			this.flags1SpinButton.Numeric = true;
			this.table2.Add (this.flags1SpinButton);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table2 [this.flags1SpinButton]));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.flags2SpinButton = new global::LynnaLab.SpinButtonHexadecimal ();
			this.flags2SpinButton.CanFocus = true;
			this.flags2SpinButton.Name = "flags2SpinButton";
			this.flags2SpinButton.Adjustment.Upper = 255;
			this.flags2SpinButton.Adjustment.PageIncrement = 10;
			this.flags2SpinButton.Adjustment.StepIncrement = 1;
			this.flags2SpinButton.ClimbRate = 1;
			this.flags2SpinButton.Digits = ((uint)(2));
			this.flags2SpinButton.Numeric = true;
			this.table2.Add (this.flags2SpinButton);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table2 [this.flags2SpinButton]));
			w5.TopAttach = ((uint)(1));
			w5.BottomAttach = ((uint)(2));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Flags 1");
			this.table2.Add (this.label4);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table2 [this.label4]));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Flags 2");
			this.table2.Add (this.label5);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table2 [this.label5]));
			w7.TopAttach = ((uint)(1));
			w7.BottomAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Unique Gfx");
			this.table2.Add (this.label6);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table2 [this.label6]));
			w8.TopAttach = ((uint)(2));
			w8.BottomAttach = ((uint)(3));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment.Add (this.table2);
			this.frame2.Add (this.GtkAlignment);
			this.GtkLabel = new global::Gtk.Label ();
			this.GtkLabel.Name = "GtkLabel";
			this.GtkLabel.UseMarkup = true;
			this.frame2.LabelWidget = this.GtkLabel;
			this.vbox2.Add (this.frame2);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame2]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.areaSpinButton.ValueChanged += new global::System.EventHandler (this.OnAreaSpinButtonValueChanged);
			this.flags1SpinButton.ValueChanged += new global::System.EventHandler (this.OnFlags1SpinButtonValueChanged);
		}
	}
}
